# ==========================================
#        BetterRaid - Konfiguracja
#            Autor: maledziecko
# ==========================================

author: "maledziecko"

raid:
  health-multiplier: 2.0
  damage-multiplier: 2.50
  extra-mobs-multiplier: 2

  mobs-base-hp:
  RAVAGER: 150
  EVOKER: 40
  VINDICATOR: 50
  ILLUSIONER: 25
  WITCH: 50
  PILLAGER: 30

  mobs-damage-multiplier:
  RAVAGER: 3.0
  EVOKER: 3.0
  VINDICATOR: 2.5
  ILLUSIONER: 2.0
  WITCH: 1.5
  PILLAGER: 15

  messages:
  prefix: "&8[&cBetterRaid&8] "
  no-permission: "&cBrak uprawnień!"
  config-reloaded: "&aPrzeładowano config!"
  raid-started: "&aRozpoczęto rajd z potężnymi falami!"