name: BetterRaid
version: '1.0'
main: pl.betterraid.BetterRaid
api-version: '1.20'
author: maledziecko

commands:
  betterraid:
    description: Glowna komenda pluginu BetterRaid
    permission: betterraid.admin
    usage: /betterraid <reload|spawnboss>
    aliases: [raid]
  
  permissions:
  betterraid.admin:
    description: Dostęp do komend administracyjnych BetterRaid
    default: op
  betterraid.broadcast:
    description: Dostęp do wysyłania ogłoszeń na środek ekranu
    default: op